# Generated by Django 6.0.5 on 2026-05-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('drink', models.CharField(max_length=50)),
                ('num_drink', models.IntegerField(default=0, max_length=10)),
                ('num_food', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
